minimumReleaseAgeExclude:
  - '@vitest/expect@4.1.8'
  - '@vitest/mocker@4.1.8'
  - '@vitest/pretty-format@4.1.8'
  - '@vitest/runner@4.1.8'
  - '@vitest/snapshot@4.1.8'
  - '@vitest/spy@4.1.8'
  - '@vitest/utils@4.1.8'
  - vite@8.0.16
  - vitest@4.1.8
shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@types/qs': ^6.15.1
  '@vitest/coverage-v8': 3.0.8
  ky: ^2.0.2
  parse-sse: ^0.1.0
  qs: ^6.15.2
catalogs:
  cli:
    '@antfu/eslint-config': ^9.0.0
    '@antfu/ni': ^30.1.0
    bumpp: ^11.1.0
    eslint: ^10.4.1
    lint-staged: ^17.0.7
    simple-git-hooks: ^2.13.1
    tsx: ^4.22.4
    typescript: ^6.0.3
    unbuild: ^3.6.1
    vite: ^8.0.16
  inlined:
    '@antfu/utils': ^9.3.0
  testing:
    vitest: ^4.1.8
    vitest-package-exports: ^0.1.1
    yaml: ^2.9.0
  types:
    '@types/node': ^24.12.3
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
allowBuilds:
  esbuild: true
  simple-git-hooks: true
